# Generated by Django 4.1.4 on 2023-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='appart',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='bdg',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
