# Generated by Django 4.1.4 on 2022-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_good_order_typeofdelivery_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
