# Generated by Django 4.1.4 on 2023-01-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_feedback_creation_date_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofdelivery',
            options={'verbose_name': 'type of delivery', 'verbose_name_plural': 'type of deliveries'},
        ),
        migrations.AddField(
            model_name='good',
            name='sold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='index',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
