# Generated by Django 4.1.4 on 2023-01-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_typeofdelivery_options_good_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_category/'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='index',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
