# Generated by Django 4.1.4 on 2023-01-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_image_good_is_active_alter_good_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='good',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='good',
            new_name='product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
