# Generated by Django 4.1.4 on 2023-01-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
