# Generated by Django 4.1.4 on 2023-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
