# Generated by Django 4.1.4 on 2023-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_delivery_comment_alter_delivery_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=256, verbose_name='website url')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
